import ProfileCard from "@/components/Cards/ProfileCard";
import getServerUser from "@/libs/server/getServerUser";
import { cookies } from "next/headers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({ children }) {
  const user = await getServerUser();
  const cookieStore = cookies();
  const token = cookieStore.has("token");
  return (
    <main>
      <section className="w-full">
        <div className="w-full max-w-6xl mx-auto px-2 py-4">
          <div className="flex flex-col-reverse md:flex-row gap-2 md:gap-8">
            <div className="w-full max-w-3xl">{children}</div>
            <div className="w-full md:w-fit my-4 md:my-8">
              <ProfileCard user={user} token={token} />
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
