import ProfileCard from "@/components/Cards/ProfileCard";
import getServerUser from "@/libs/server/getServerUser";
import { cookies } from "next/headers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({ children }) {
  const user = await getServerUser();
  const cookieStore = cookies();
  const token = cookieStore.has("token");
  return (
    <main className="flex flex-col md:flex-row gap-2 md:gap-8">
      <aside className="h-fit">
        <ProfileCard user={user} token={token} />
      </aside>
      <section className="w-full px-4 py-4 mx-auto">
        <div className="w-full">{children}</div>
      </section>
    </main>
  );
}
