import ProfileCard from "@/components/Cards/ProfileCard";
import getServerUser from "@/libs/server/getServerUser";
import { cookies } from "next/headers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({ children }) {
  const user = await getServerUser();
  const cookieStore = cookies();
  const token = cookieStore.has("token");
  return (
    <main className="flex flex-col lg:flex-row gap-2 h-full">
      <aside className="lg:h-screen bg-slate-100 dark:bg-slate-900 ">
        <ProfileCard user={user} token={token} />
      </aside>
      <section className="w-full px-4 py-4 mx-auto">
        <div className="w-full max-w-7xl mx-auto">{children}</div>
      </section>
    </main>
  );
}
