import { Inter, Roboto } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["greek"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-200`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
