import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import StoreProvider from "@/libs/app/StoreProvider";
import getServerUser from "@/libs/server/getServerUser";
import { Roboto } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["greek"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  
  const user = await getServerUser();
  const cookieStore = cookies();
  const token = cookieStore.has("token")
    ? cookieStore.get("token").value
    : null;
  return (
    <html className="dark" lang="en">
      <body
        className={`${roboto.className} bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-200`}
      >
        <StoreProvider user={user} token={token}>
          <Navbar token={token} user={user} />
          {children}
        </StoreProvider>
        <Footer />
      </body>
    </html>
  );
}
